# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

orbs:
  angular: okode/angular@1.0.60

jobs:

  deploy:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Download CF CLI
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v


      - run:
          name: NPM install
          command: |
            npm install

      - run:
          name: Build static site
          command: |
            ./node_modules/.bin/ng --version
            ./node_modules/.bin/ng build --configuration=dev --prod=false --outputHashing=all
            cd dist
            touch Staticfile
            echo "{ \"version\" : \"circle-${CIRCLE_BUILD_NUM}\", \"build_data\" :  \"`date`\"} " > version.html

      - run:
          name: Deploy Client
          command: |
            # Documentation for service accounts here: https://cloud.gov/docs/services/cloud-gov-service-account/
            cd ~/repo/dist
            export SPACE="$CIRCLE_BRANCH"
            export UNAME_VAR=CF_USERNAME_${SPACE}
            export PWD_VAR=CF_PASSWORD_${SPACE}
            cf login -a https://api.fr.cloud.gov -u ${!UNAME_VAR} -p ${!PWD_VAR} -o gsa-ogp-srt -s ${SPACE}
            cf push -m 64M srt-client-dev

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: dev

  build-wait-deploy:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              only:
                - staging
                - prod

      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - staging
                - prod
