# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0-browsers
        environment:
          NODE_ENV: circleci 
#          CC_TEST_REPORTER_ID: b0a733c16dd63abc6cb21bf9956550d57e05724bc92e58892b306af99963a261

      - image: circleci/postgres:9.6.8
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: srt
          POSTGRES_PASSWORD: srtpass

#    parallelism: 3

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt update

      - run: npm install

      - run: ./node_modules/.bin/webdriver-manager update
      - run: ./node_modules/.bin/webdriver-manager start --detach

      - run:
         name: Run the Tests
         environment:
           NODE_ENV: circle
#          command: npm run circleci
         command: |
              npm run test


