name: Unit Testing Feature Branches

on:
  push:
    branches:
      - 'feature/*'

jobs:
    unit-test:
        name: Unit Test Job
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v3.5.3          
        - 
            name: Running Unit Tests
            run: yarn ngtest